# Copyright (c) 2023, Frappe Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

import frappe
from frappe.desk.form.assign_to import add as assign
from frappe.desk.form.assign_to import remove as unassign
from frappe.model.document import Document


class CRMTask(Document):
	# begin: auto-generated types
	# This code is auto-generated. Do not modify anything in this block.

	from typing import TYPE_CHECKING

	if TYPE_CHECKING:
		from frappe.types import DF

		assigned_to: DF.Link | None
		description: DF.TextEditor | None
		due_date: DF.Datetime | None
		name: DF.Int | None
		priority: DF.Literal["Low", "Medium", "High"]
		reference_docname: DF.DynamicLink | None
		reference_doctype: DF.Link | None
		start_date: DF.Date | None
		status: DF.Literal["Backlog", "Todo", "In Progress", "Done", "Canceled"]
		title: DF.Data
	# end: auto-generated types

	def after_insert(self):
		self.assign_to()

	def validate(self):
		if self.is_new() or not self.assigned_to:
			return

		if self.get_doc_before_save().assigned_to != self.assigned_to:
			self.unassign_from_previous_user(self.get_doc_before_save().assigned_to)
			self.assign_to()

	def unassign_from_previous_user(self, user: str | None):
		if user:
			unassign(self.doctype, self.name, user)

	def assign_to(self):
		if self.assigned_to:
			assign(
				{
					"assign_to": [self.assigned_to],
					"doctype": self.doctype,
					"name": self.name,
					"description": self.title or self.description,
				}
			)

	@staticmethod
	def default_list_data():
		columns = [
			{
				"label": "Title",
				"type": "Data",
				"key": "title",
				"width": "16rem",
			},
			{
				"label": "Reference Doc",
				"type": "Dynamic Link",
				"key": "reference_docname",
				"width": "12rem",
			},
			{
				"label": "Status",
				"type": "Select",
				"key": "status",
				"width": "8rem",
			},
			{
				"label": "Priority",
				"type": "Select",
				"key": "priority",
				"width": "8rem",
			},
			{
				"label": "Due Date",
				"type": "Date",
				"key": "due_date",
				"width": "8rem",
			},
			{
				"label": "Assigned To",
				"type": "Link",
				"key": "assigned_to",
				"width": "10rem",
			},
			{
				"label": "Last Modified",
				"type": "Datetime",
				"key": "modified",
				"width": "8rem",
			},
		]

		rows = [
			"name",
			"title",
			"description",
			"assigned_to",
			"due_date",
			"status",
			"priority",
			"reference_doctype",
			"reference_docname",
			"modified",
		]
		return {"columns": columns, "rows": rows}

	@staticmethod
	def parse_list_data(tasks):
		"""Annotate each task with the title of the record it references.

		reference_docname is the referenced record's name, which is a readable
		title for some doctypes and an autogenerated id for others. Resolve the
		title once per referenced doctype so the list can show what the task is
		for instead of an id.
		"""
		if not tasks:
			return tasks

		references = {}
		for task in tasks:
			doctype = task.get("reference_doctype")
			docname = task.get("reference_docname")
			if doctype and docname:
				references.setdefault(doctype, set()).add(docname)

		titles = {}
		for doctype, docnames in references.items():
			try:
				title_field = frappe.get_meta(doctype).get_title_field()
			except frappe.DoesNotExistError:
				continue

			if title_field == "name":
				continue

			# get_list, not get_all: a user who cannot read the referenced
			# record falls back to its name rather than being handed its title.
			for row in frappe.get_list(
				doctype,
				filters={"name": ("in", list(docnames))},
				fields=["name", title_field],
				limit_page_length=0,
			):
				titles[(doctype, row.get("name"))] = row.get(title_field)

		for task in tasks:
			key = (task.get("reference_doctype"), task.get("reference_docname"))
			task["_reference_title"] = titles.get(key) or task.get("reference_docname")

		return tasks

	@staticmethod
	def default_kanban_settings():
		return {
			"column_field": "status",
			"title_field": "title",
			"kanban_fields": '["description", "priority", "creation"]',
		}
